-- phpMyAdmin SQL Dump
-- version 4.8.5
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Feb 08, 2020 at 05:50 PM
-- Server version: 10.1.38-MariaDB
-- PHP Version: 7.3.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `mcqproject`
--

-- --------------------------------------------------------

--
-- Table structure for table `addquestion`
--

CREATE TABLE `addquestion` (
  `module` varchar(100) NOT NULL,
  `question` varchar(10000) NOT NULL,
  `option_A` varchar(1000) NOT NULL,
  `option_B` varchar(1000) NOT NULL,
  `option_C` varchar(1000) NOT NULL,
  `option_D` varchar(1000) NOT NULL,
  `option_Ans` varchar(1000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `addquestion`
--

INSERT INTO `addquestion` (`module`, `question`, `option_A`, `option_B`, `option_C`, `option_D`, `option_Ans`) VALUES
('CS', ' I/O function allows to exchange data directly between an', 'Process States', 'Registers', 'I/O module and the processor', 'I/O devices', 'I/O module and the processor'),
('CS', ' Cache memory is intended to provide memory access			', 'Fastest', 'Slow', 'Very Slow ', 'Comparatively Fast ', 'Fastest'),
('CS', 'Primary element used for data storage is said to be', 'Monitor', 'Main storage ', 'secondary storage ', 'Keyboard', 'secondary storage '),
('CS', 'Interrupts are provided primarily as a way to', 'Improve processor utilization ', 'Improve processor execution ', 'Improve processor control ', 'Improve processor speed ', 'Improve processor utilization '),
('CS', 'Index register involves adding an', 'Index', 'Instruction', 'Information', 'I/O device ', 'Index'),
('Java', 'Which is a reserved word in the Java programming language?', 'method', 'native', 'subclasses', 'reference', 'native'),
('Java', 'Which is a valid keyword in java?', 'interface', 'string', 'Float', 'unsigned', 'interface'),
('Java', 'Under which package is the string class encapsulated?', 'java.lang', ' java.util', ' java.io', 'java.awt', 'java.lang'),
('Java', 'In Iterator, hasMoreElements() method of Enumeration has been changed to:', 'hasNextElement()', 'isNext()', 'hasNext()', 'name remains same', 'hasNext()'),
('Java', 'Which one of the following will declare an array and initialize it with five numbers?', 'Array a = new Array(5);', 'int [] a = {23,22,21,20,19};', 'int a [] = new int[5];', 'int [5] array;', 'int [] a = {23,22,21,20,19};'),
('Java', 'Which is the valid declarations within an interface definition?', 'public double methoda();', 'public final double methoda();', 'static void methoda(double d1);', 'protected void methoda(double d1);', 'public double methoda();'),
('Java', 'Which one is a valid declaration of a boolean?', 'boolean b1 = 0;', 'boolean b2 = \'false\';', 'boolean b3 = false;', 'boolean b4 = Boolean.false();', 'boolean b3 = false;'),
('Java', 'Which is a valid declarations of a String?', 'String s1 = null;', 'String s2 = null;', 'String s3 = (String) \'abc\';', 'String s4 = (String) \'\\ufeed\';', 'String s1 = null;'),
('Java', 'What is the numerical range of a char?', '-128 to 127', '-(215) to (215) - 1', '0 to 32767', '0 to 65535', '0 to 65535'),
('Java', 'Which keyword is used for the block to handle the exceptions generated by try block?\n', 'Catch', 'Final', 'throw', 'try', 'Catch'),
('Java', 'What is used to execute parameterized query?', 'Statement interface', 'PreparedStatement interface', 'ResultSet interface', 'None of the above', 'PreparedStatement interface'),
('Java', 'Which objects are used by RMI for communicating with the remote object?', 'Stub', 'Skeleton', 'Both A & B', 'None of the above', 'Both A & B'),
('Python', 'Which among them will produce {\'a\', \'b\', \'c\'}?\n\nS = [[\'him\', \'sell\'], [90, 28, 43]]\n\nS[0][1][1]', 'Tuple(\'\'abc\'\')', 'List(\'\'abc\'\')', 'Set(\'\'abac\'\')', ' None of the above.', ' None of the above.'),
('Python', 'Which method is used to convert raw byte data to a string?', ' Encode()', 'Decode()', 'Convert()', 'tostring()', 'Decode()'),
('Python', 'Select the reserved keyword in python', 'else', 'import', 'raise', 'All of these', 'All of these'),
('Python', 'Which of the following symbols are used for comments in Python?', '//', '\"', '/*/', '#', '#'),
('Python', 'Which keyword is used to define methods in Python?', 'function', 'def', 'method', 'All of these', 'def'),
('Python', 'Which of the following is correct way to declare string variable in Python?', ' fruit = \'banana\'', 'fruit = \"banana\"', 'fruit = banana', 'fruit = (banana)', ' fruit = \'banana\''),
('Python', 'Which predefined Python function is used to find length of string?', 'length()', ' len()', 'strlen()', 'stringlength()', ' len()'),
('Python', 'Syntax of constructor in Python?', 'def __init__()', 'def _init_()', '_init_()', 'All of these', 'def __init__()'),
('Python', 'What is correct syntax to copy one list into another?', 'listA = listB[]', 'listA = listB[:]', 'listA = listB[]()', 'listA = listB', 'listA = listB[:]'),
('Python', 'The format function, when applied on a string returns :', 'list', 'bool', 'int', 'str', 'str'),
('JavaScript', ' Why so JavaScript and Java have similar name?', 'JavaScript is a stripped-down version of Java', 'JavaScript\'s syntax is loosely based on Java\'s', 'They both originated on the island of Java', 'None of the above', 'JavaScript is a stripped-down version of Java'),
('JavaScript', '----------JavaScript is a stripped-down version of Java', 'Microsoft', 'Navigator', 'LiveWire', 'Native', 'LiveWire'),
('JavaScript', 'What are variables used for in JavaScript Programs?', ' Storing numbers, dates, or other values', 'Varying randomly', 'Causing high-school algebra flashbacks', 'None of the above', 'Storing numbers, dates, or other values'),
('JavaScript', 'Which of the following can\'t be done with client-side JavaScript?', 'Validating a form', 'Sending a form\'s contents by email', 'Storing the form\'s contents to a database file on the server', 'None of the above', 'Storing the form\'s contents to a database file on the server'),
('JavaScript', ' Which of the following are capabilities of functions in JavaScript?', 'Return a value', 'Accept parameters and Return a value', 'Accept parameters', 'None of the above', 'Accept parameters'),
('JavaScript', 'Which of the following is not a valid JavaScript variable name?', '2names', '_first_and_last_names', 'FirstAndLast', 'None of the above', '2names'),
('JavaScript', 'Which of the following attribute can hold the JavaScript version?', 'LANGUAGE', 'SCRIPT', 'VERSION', 'None of the above', 'LANGUAGE'),
('JavaScript', 'Inside which HTML element do we put the JavaScript?', '<js>', '<scripting>', '<script>', '<javascript>', '<script>'),
('JavaScript', 'Choose the server-side JavaScript object?', 'FileUpLoad', 'Function', 'File', 'Date', 'File'),
('JavaScript', 'Choose the client-side JavaScript object?', 'Database', 'Cursor', 'Client', 'FileUpLoad', 'FileUpLoad');

-- --------------------------------------------------------

--
-- Table structure for table `admin`
--

CREATE TABLE `admin` (
  `name` varchar(100) NOT NULL,
  `password` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `admin`
--

INSERT INTO `admin` (`name`, `password`, `email`) VALUES
('admin', 'admin', 'admin');

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

CREATE TABLE `user` (
  `name` varchar(100) NOT NULL,
  `password` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`name`, `password`, `email`) VALUES
('a', 'a', 'a'),
('', '', '');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
